### PR TITLE
396 add iOS app

### PR DESCRIPTION
**Pull request by mort3za**
# Issue Being Addressed

#396 

# Type of PR

[ ] Bug Fix
[ ] Refactor
[x] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For New Features:** What feature are we adding? Explain your technical approach to doing this.

Add iOS app by Capacitor

# How to Test/Reproduce

`yarn install && yarn capacitor:build:production`, then if you have Xcode run `npx cap open ios`, see this video for the rest of work: https://youtu.be/y_UUjPkxlZ0?t=1034

### CODE REVIEW

**Comment by mort3za** [comment]
The normal way of creating a binary output for iOS is to build it with Xcode on a Macbook, but I'm looking for another way. Seems Appflow can do it https://ionicframework.com/docs/appflow

**Comment by mort3za** [comment]
@paulchrisluke could you put the app on App Store? If yes, I should merge this.

**Comment by paulchrisluke** [comment]
I don't have a mac but maybe can find one

**Comment by joeelia** [comment]
I was submitting to TestFlight and it seems I need a private key file? @mort3za 
Screen Shot 2020-11-14 at 1 34 48 PM

**Pull request closed without merging**
