### PR TITLE
Feature: Customer Home View

### PR DESCRIPTION
**Pull request by sally**
# Description

This PR addresses Issue #11.  We make a basic prototype of what the Customer Home view will look like. We hardcode some dummy data into the view as placeholders.

* `89d35ab`: We add one extension for height utilities in Tailwind config. We need this to set the height of the Menu Header (and later, Nav Headers)

* `ce12c47`: We move the 'Button' component to a sub-folder called 'ui' where we will put more common components used across both Tenant and Customer views

* `dae0b0e`: We add the basic MenuHeader component which has the hamburger menu icon at the top left. We will use this component for the following purposes in the Customer views, as seen in the Figma designs:

image

* `b21fbd8`: We add the first iteration of the Customer Home View component.

* `3ff331b`: We add placeholder routes to access the Customer Home View component from `/`

# How to test

Go to `/` or `/shop/test-tenant-slug` and see the result

image

### CODE REVIEW

**Comment by mort3za** [comment]
Good job!  
A minor suggestion: use hyperlink for everything that is clickable, in this PR the hamburger menu toggle link. Reason: for better accessibility.

**Comment by sally** [comment]
@mort3za Thanks for the review! When you say `use hyperlink for everything that is clickable` you mean use `a` tag around it, right?

**Comment by mort3za** [comment]
Yes

**Comment by sally** [comment]
@mort3za Great, thanks! I will definitely use that when the menu icon actually becomes a link when I work on #10.

**Pull request merged**
