### PR TITLE
220 Update bottom navigation

### PR DESCRIPTION
**Pull request by mort3za**
# Issue Being Addressed

#220

# Type of PR

[ ] Bug Fix
[ ] Refactor
[ ] New Feature
[x] Update to Existing Feature
[ ] Other (state below)

# Description

**For Feature Updates:** What feature are we updating? Explain your technical approach to doing this.  
- Bottom navigation design updated.  
- Updated SVG icons (removed white spaces in viewbox)
- Enabled bottom navigation for all routes of client page

# Screenshots/casts

localhost_8080_tenant_tttest-110

# Additional details

Fixed the z-index and max width of snackbar (terms and conditions)

### CODE REVIEW

**Review by paulchrisluke — APPROVED** [review]
Ux approved

**Comment by paulchrisluke** [comment]
Requesting review from @giteshk11 since of his work is related

**Review by giteshk11 — COMMENTED** [review]
When client tab is active only that is highlighted 
9s9d3OBbl9

But when tab other tab is active all the other tabs are highlighted
jyYqqkBdrg
@mort3za  @paulchrisluke

**Comment by mort3za** [comment]
@giteshk11 That's ok for now, the right side links are not yet connected to the actual pages.

**Pull request merged**
