### PR TITLE
Client notes

### PR DESCRIPTION
**Pull request by abdullahcalisir12**
# Issue Being Addressed
#73 #98 #101 
Put the issue(s) # that your PR is addressing here. e.g. #15, #29

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[ ] Refactor
[x] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For Bug Fixes:** What was the root cause? How do your changes fix the bug effectively?

**For Refactors:** What are we refactoring and why? How do your changes address this need for refactoring?

**For New Features:** What feature are we adding? Explain your technical approach to doing this.
Client notes page created

**For Feature Updates:** What feature are we updating? Explain your technical approach to doing this.

**For Other:** State what 'type' of PR yours is and elaborate on the PR's technical content.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Go to any client detail page click notes expansion panel
2. try to add new note update new note delete one

# Screenshots/casts
image
image
image

If applicable, include any relevant screenshot or screencasts of your changes.

# Additional Context

Provide any additional notes that you think would help effective review of your code.

### CODE REVIEW

**Comment by abdullahcalisir12** [comment]
@paulchrisluke if backend sends me created date yeah I can.

**Comment by paulchrisluke** [comment]
ok I made a backend issue here @ctyar https://github.com/whynotearth/meredith-core/issues/268

may as well add timestamp to the backend endpoints just in case. We wont show it in ui, but good to have.

Will also need edit times, so we can show that in the ui

**Comment by paulchrisluke** [comment]
@abdullahcalisir12 , client note date/times are ready in backend. Hope you're having a good vacation!

**Comment by abdullahcalisir12** [comment]
> @abdullahcalisir12 , client note date/times are ready in backend. Hope you're having a good vacation!

thank you @paulchrisluke I added date to client notes you can check it

**Pull request merged**
