### PR TITLE
305 style - tenant home, navigation bottom, my account

### PR DESCRIPTION
**Pull request by mort3za**
# Issue Being Addressed

#305 

# Type of PR

[ ] Bug Fix
[ ] Refactor
[ ] New Feature
[x] Update to Existing Feature
[ ] Other (state below)

# Description

**For Feature Updates:** What feature are we updating? Explain your technical approach to doing this.

- My account
- home
- bottom navigation
- client inner pages WIP

### CODE REVIEW

**Comment by paulchrisluke** [comment]
image
this font is champaign and limousine, is there a way 

Is there a way to make the pattern extend all the way here?

**Comment by paulchrisluke** [comment]
image
this font is champaign and limousine, is there a way 

Is there a way to make the pattern extend all the way here? 
image

**Comment by mort3za** [comment]
Sure, will extend it.  
Will fix the font.

**Comment by paulchrisluke** [comment]
image
can this be centered so its in alignment with the buttons? SO CLOSE LOOKING GREAT

**Comment by mort3za** [comment]
Just centering the button texts yea? (icons current position is good?)

**Pull request merged**
