### PR TITLE
Meta: Pull Request Template

### PR DESCRIPTION
**Pull request by sally**
# Description

We add a pull request template to be regularly used by developers working on the project. This should help PR descriptions be more focused and thorough which should help produce faster and more effective reviews which should help the codebase be more navigable, extendable, rack up less tech debt, etc. :)

Go [here](https://github.com/whynotearth/BrowTricks/blob/bc76c092dda1f8c2fee1b738a9c67d0f7ce3c89c/.github/pull_request_template.md) to view the template in markdown form, which should be easier to read than in diff form.

Any and all feedback appreciated, especially from other devs.

### CODE REVIEW

**Comment by paulchrisluke** [comment]
@mort3za @atharva3010 could you take a look at this template for our PR's? We want to start templating our work to make it easier for everyone to review as well as new contributors. I think it looks good on my end. @bamboochow too.

https://github.com/whynotearth/BrowTricks/blob/bc76c092dda1f8c2fee1b738a9c67d0f7ce3c89c/.github/pull_request_template.md

**Comment by mort3za** [comment]
:+1:

**Comment by sally** [comment]
Hey @abdullahcalisir12 @smebrahimi @chris-saburo I asked @paulchrisluke if I could tag you on this as we are planning to use a PR template in our projects some time soon moving forward to improve the code review process. Would y'all let me know of any feedback you might have? Thank you!

**Comment by atharva3010** [comment]
This template looks good! :+1:

**Comment by smebrahimi** [comment]
It looks good.

**Comment by abdullahcalisir12** [comment]
it looks cool,I think we need a good template for bug and issues too. 
Similar to this
https://github.com/devspace/awesome-github-templates

**Comment by sally** [comment]
@abdullahcalisir12 Thanks for your feedback! Hmm, yeah. I agree it would be nice to fully separate out the template into separate bug report/feature/update/other templates. I don't think GitHub has full support around it though: 

I'd like the PR description to populate automatically when someone is opening a PR instead of someone having to go copy and paste the correct template. Then, the PR opener can tick the correct box for the 'type' of PR it is themselves in the 'What kind of PR is this? (check all that apply)' section [here](https://github.com/whynotearth/BrowTricks/blob/bc76c092dda1f8c2fee1b738a9c67d0f7ce3c89c/.github/pull_request_template.md#what-kind-of-pr-is-this-check-all-that-apply).

For now let's keep one template that the PR opener will manually indicate the 'type' (bug fix/update/new feature/other) and then expand later if we find the real need to.

**Comment by sally** [comment]
Going to merge this and start using it in BrowTricks for now. I would love to port it into our other projects too but I think it's good idea to use it myself to generate some examples and get my own feedback when using it :)

**Pull request merged**
