### PR TITLE
fixed router transitions #255

### PR DESCRIPTION
**Pull request by giteshk11**
# Issue Being Addressed
#255 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[x] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description
**For Refactors:** What are we refactoring and why? How do your changes address this need for refactoring?
Refactored classes that handling animations

# Screenshots/casts
If applicable, include any relevant screenshot or screencasts of your changes.
ezgif com-video-to-gif

### CODE REVIEW

**Review by paulchrisluke — CHANGES_REQUESTED** [review]
this is looking great! I think the transitions between the bottom nav pages should have a spinner:

https://github.com/whynotearth/BrowTricks/issues/174


this already exists in some page transitions, like moving from client list into a single client

https://deploy-preview-262--browtricks.netlify.app/tenant/salon-2-95/clients
>
https://deploy-preview-262--browtricks.netlify.app/tenant/salon-2-95/clients/103/edit

this gives the page time to load and makes the app feel less "jumpy"

**Comment by paulchrisluke** [comment]
@mort3za I'm on stream with @giteshk11 , if you had time to clean up our transitions that'd be great while he finishes my account

**Comment by mort3za** [comment]
Sorry can't do that, needs a fresh mind, tired right now.

**Comment by mort3za** [comment]
@giteshk11 Thank you so much!

**Pull request merged**
