### PR TITLE
Removed avatar icon from tenanthome.vue and home.vue #249

### PR DESCRIPTION
**Pull request by giteshk11**
# Issue Being Addressed
#249 

# Type of PR

Put an `x` in the brackets for the type(s) of PR this is. You may tick more than one.

[ ] Bug Fix
[x] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

**For Refactors:** What are we refactoring and why?
Removed the avatar icon because it was moved to bottom navigation.

# How to Test/Reproduce

Provide steps on how one can test your changes here. e.g.
1. Log in with your account
2. Go to the home page
3. See the updated  top navbar

# Screenshots/casts
Screen Shot 2020-08-30 at 14 29 49

### CODE REVIEW

**Comment by paulchrisluke** [comment]
This looks good. In our new design we do not have navigation in the top left of the top nav bar. Navigation is done entirely by the bottom navigation. Can you remove the back arrow from the clients page and the hamburger menu from the homepage?

You will also need to add the bottom navigation to browtricksbeauty.com home page, so people can hit the sign in when they hit my account

**Comment by giteshk11** [comment]
Can you create a new issue with screenshots so that I can get to know a little better or add the screenshots in the comment down below?

**Review by paulchrisluke — APPROVED** [review]

**Comment by bamboochow** [comment]
> This looks good. In our new design we do not have navigation in the top left of the top nav bar. Navigation is done entirely by the bottom navigation. Can you remove the back arrow from the clients page and the hamburger menu from the homepage?
> 
> You will also need to add the bottom navigation to browtricksbeauty.com home page, so people can hit the sign in when they hit my account

@paulchrisluke  @giteshk11  This isn't correct - we will have settings pages that requires the back button at on the navigation according to our new tiktok style settings breakdown, while the core functional pages will not need navigation

**Comment by paulchrisluke** [comment]
should this still be merged, or was it taken care of in the latest push? @giteshk11

**Comment by giteshk11** [comment]
need to merge

**Pull request merged**
